[package]
name = "sim-site-powerproject"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"
description = "Powerproject and Project for the web site placement for SIM Gantt documents."
readme = "README.md"
publish = false
repository = "https://github.com/sim-nest/sim-construction"
homepage = "https://github.com/sim-nest/sim-construction"

[features]
default = []
powerproject-ole = []

[dependencies]
sim-codec-mspdi = { version = "0.1.0", path = "../sim-codec-mspdi" }
sim-cookbook = { version = "0.2.0" }
sim-kernel = { version = "0.2.0" }
sim-lib-doc-core = { version = "0.1.0", git = "https://github.com/sim-nest/sim-office", rev = "eb617e4fd3c50fc51bcdb6a11ea5a8bbae4d1a48" }
sim-lib-doc-site = { version = "0.1.0", git = "https://github.com/sim-nest/sim-office", rev = "eb617e4fd3c50fc51bcdb6a11ea5a8bbae4d1a48" }
sim-lib-gantt = { version = "0.1.0", git = "https://github.com/sim-nest/sim-office", rev = "2c76395bf66978822210f2397a03482b1f429da8" }

[build-dependencies]
sim-cookbook = { version = "0.2.0" }

[dev-dependencies]
time = "0.3"

[lints]
workspace = true
